/* Auto-generated by genmsg_cpp for file /home/ahmed/me597/ROS_packages/clearpath_horizon/msg/PowerStatus.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_POWERSTATUS_H
#define CLEARPATH_HORIZON_MESSAGE_POWERSTATUS_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"
#include "clearpath_horizon/PowerSource.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct PowerStatus_ : public ros::Message
{
  typedef PowerStatus_<ContainerAllocator> Type;

  PowerStatus_()
  : header()
  , sources()
  {
  }

  PowerStatus_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , sources(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::clearpath_horizon::PowerSource_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::clearpath_horizon::PowerSource_<ContainerAllocator> >::other >  _sources_type;
  std::vector< ::clearpath_horizon::PowerSource_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::clearpath_horizon::PowerSource_<ContainerAllocator> >::other >  sources;


  ROS_DEPRECATED uint32_t get_sources_size() const { return (uint32_t)sources.size(); }
  ROS_DEPRECATED void set_sources_size(uint32_t size) { sources.resize((size_t)size); }
  ROS_DEPRECATED void get_sources_vec(std::vector< ::clearpath_horizon::PowerSource_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::clearpath_horizon::PowerSource_<ContainerAllocator> >::other > & vec) const { vec = this->sources; }
  ROS_DEPRECATED void set_sources_vec(const std::vector< ::clearpath_horizon::PowerSource_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::clearpath_horizon::PowerSource_<ContainerAllocator> >::other > & vec) { this->sources = vec; }
private:
  static const char* __s_getDataType_() { return "clearpath_horizon/PowerStatus"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "f246c359530c58415aee4fe89d1aca04"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
PowerSource[] sources\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: clearpath_horizon/PowerSource\n\
float32 charge\n\
int16 capacity\n\
bool present\n\
bool in_use\n\
uint8 description\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, sources);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, sources);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(sources);
    return size;
  }

  typedef boost::shared_ptr< ::clearpath_horizon::PowerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::PowerStatus_<ContainerAllocator>  const> ConstPtr;
}; // struct PowerStatus
typedef  ::clearpath_horizon::PowerStatus_<std::allocator<void> > PowerStatus;

typedef boost::shared_ptr< ::clearpath_horizon::PowerStatus> PowerStatusPtr;
typedef boost::shared_ptr< ::clearpath_horizon::PowerStatus const> PowerStatusConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::PowerStatus_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::PowerStatus_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::PowerStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f246c359530c58415aee4fe89d1aca04";
  }

  static const char* value(const  ::clearpath_horizon::PowerStatus_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf246c359530c5841ULL;
  static const uint64_t static_value2 = 0x5aee4fe89d1aca04ULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::PowerStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/PowerStatus";
  }

  static const char* value(const  ::clearpath_horizon::PowerStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::PowerStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
PowerSource[] sources\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: clearpath_horizon/PowerSource\n\
float32 charge\n\
int16 capacity\n\
bool present\n\
bool in_use\n\
uint8 description\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::PowerStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::PowerStatus_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::PowerStatus_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::PowerStatus_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.sources);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PowerStatus_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::PowerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::PowerStatus_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sources[]" << std::endl;
    for (size_t i = 0; i < v.sources.size(); ++i)
    {
      s << indent << "  sources[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::clearpath_horizon::PowerSource_<ContainerAllocator> >::stream(s, indent + "    ", v.sources[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_POWERSTATUS_H

