/* Auto-generated by genmsg_cpp for file /home/ahmed/me597/ROS_packages/clearpath_horizon/msg/PowerSource.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_POWERSOURCE_H
#define CLEARPATH_HORIZON_MESSAGE_POWERSOURCE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace clearpath_horizon
{
template <class ContainerAllocator>
struct PowerSource_ : public ros::Message
{
  typedef PowerSource_<ContainerAllocator> Type;

  PowerSource_()
  : charge(0.0)
  , capacity(0)
  , present(false)
  , in_use(false)
  , description(0)
  {
  }

  PowerSource_(const ContainerAllocator& _alloc)
  : charge(0.0)
  , capacity(0)
  , present(false)
  , in_use(false)
  , description(0)
  {
  }

  typedef float _charge_type;
  float charge;

  typedef int16_t _capacity_type;
  int16_t capacity;

  typedef uint8_t _present_type;
  uint8_t present;

  typedef uint8_t _in_use_type;
  uint8_t in_use;

  typedef uint8_t _description_type;
  uint8_t description;


private:
  static const char* __s_getDataType_() { return "clearpath_horizon/PowerSource"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "adbe384d7d69a337a7f2b6bf1d0139cb"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 charge\n\
int16 capacity\n\
bool present\n\
bool in_use\n\
uint8 description\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, charge);
    ros::serialization::serialize(stream, capacity);
    ros::serialization::serialize(stream, present);
    ros::serialization::serialize(stream, in_use);
    ros::serialization::serialize(stream, description);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, charge);
    ros::serialization::deserialize(stream, capacity);
    ros::serialization::deserialize(stream, present);
    ros::serialization::deserialize(stream, in_use);
    ros::serialization::deserialize(stream, description);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(charge);
    size += ros::serialization::serializationLength(capacity);
    size += ros::serialization::serializationLength(present);
    size += ros::serialization::serializationLength(in_use);
    size += ros::serialization::serializationLength(description);
    return size;
  }

  typedef boost::shared_ptr< ::clearpath_horizon::PowerSource_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::PowerSource_<ContainerAllocator>  const> ConstPtr;
}; // struct PowerSource
typedef  ::clearpath_horizon::PowerSource_<std::allocator<void> > PowerSource;

typedef boost::shared_ptr< ::clearpath_horizon::PowerSource> PowerSourcePtr;
typedef boost::shared_ptr< ::clearpath_horizon::PowerSource const> PowerSourceConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::PowerSource_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::PowerSource_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::PowerSource_<ContainerAllocator> > {
  static const char* value() 
  {
    return "adbe384d7d69a337a7f2b6bf1d0139cb";
  }

  static const char* value(const  ::clearpath_horizon::PowerSource_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xadbe384d7d69a337ULL;
  static const uint64_t static_value2 = 0xa7f2b6bf1d0139cbULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::PowerSource_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/PowerSource";
  }

  static const char* value(const  ::clearpath_horizon::PowerSource_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::PowerSource_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 charge\n\
int16 capacity\n\
bool present\n\
bool in_use\n\
uint8 description\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::PowerSource_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::clearpath_horizon::PowerSource_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::PowerSource_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.charge);
    stream.next(m.capacity);
    stream.next(m.present);
    stream.next(m.in_use);
    stream.next(m.description);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PowerSource_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::PowerSource_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::PowerSource_<ContainerAllocator> & v) 
  {
    s << indent << "charge: ";
    Printer<float>::stream(s, indent + "  ", v.charge);
    s << indent << "capacity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.capacity);
    s << indent << "present: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.present);
    s << indent << "in_use: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.in_use);
    s << indent << "description: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.description);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_POWERSOURCE_H

