/* Auto-generated by genmsg_cpp for file /home/ahmed/me597/ROS_packages/clearpath_horizon/msg/RawEncoders.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_RAWENCODERS_H
#define CLEARPATH_HORIZON_MESSAGE_RAWENCODERS_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct RawEncoders_ : public ros::Message
{
  typedef RawEncoders_<ContainerAllocator> Type;

  RawEncoders_()
  : header()
  , ticks()
  {
  }

  RawEncoders_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , ticks(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _ticks_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  ticks;


  ROS_DEPRECATED uint32_t get_ticks_size() const { return (uint32_t)ticks.size(); }
  ROS_DEPRECATED void set_ticks_size(uint32_t size) { ticks.resize((size_t)size); }
  ROS_DEPRECATED void get_ticks_vec(std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other > & vec) const { vec = this->ticks; }
  ROS_DEPRECATED void set_ticks_vec(const std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other > & vec) { this->ticks = vec; }
private:
  static const char* __s_getDataType_() { return "clearpath_horizon/RawEncoders"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d105c5e4b407d4a68215fce86175fe75"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
int32[] ticks\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, ticks);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, ticks);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(ticks);
    return size;
  }

  typedef boost::shared_ptr< ::clearpath_horizon::RawEncoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::RawEncoders_<ContainerAllocator>  const> ConstPtr;
}; // struct RawEncoders
typedef  ::clearpath_horizon::RawEncoders_<std::allocator<void> > RawEncoders;

typedef boost::shared_ptr< ::clearpath_horizon::RawEncoders> RawEncodersPtr;
typedef boost::shared_ptr< ::clearpath_horizon::RawEncoders const> RawEncodersConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::RawEncoders_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::RawEncoders_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::RawEncoders_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d105c5e4b407d4a68215fce86175fe75";
  }

  static const char* value(const  ::clearpath_horizon::RawEncoders_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd105c5e4b407d4a6ULL;
  static const uint64_t static_value2 = 0x8215fce86175fe75ULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::RawEncoders_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/RawEncoders";
  }

  static const char* value(const  ::clearpath_horizon::RawEncoders_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::RawEncoders_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32[] ticks\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::RawEncoders_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::RawEncoders_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::RawEncoders_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::RawEncoders_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.ticks);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RawEncoders_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::RawEncoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::RawEncoders_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ticks[]" << std::endl;
    for (size_t i = 0; i < v.ticks.size(); ++i)
    {
      s << indent << "  ticks[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ticks[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_RAWENCODERS_H

