/* Auto-generated by genmsg_cpp for file /home/ahmed/me597/ROS_packages/clearpath_horizon/msg/SafetyStatus.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_SAFETYSTATUS_H
#define CLEARPATH_HORIZON_MESSAGE_SAFETYSTATUS_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct SafetyStatus_ : public ros::Message
{
  typedef SafetyStatus_<ContainerAllocator> Type;

  SafetyStatus_()
  : header()
  , flags(0)
  , estop(false)
  {
  }

  SafetyStatus_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , flags(0)
  , estop(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint16_t _flags_type;
  uint16_t flags;

  typedef uint8_t _estop_type;
  uint8_t estop;


private:
  static const char* __s_getDataType_() { return "clearpath_horizon/SafetyStatus"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "cf78d6042b92d64ebda55641e06d66fa"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
uint16 flags\n\
bool estop\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, flags);
    ros::serialization::serialize(stream, estop);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, flags);
    ros::serialization::deserialize(stream, estop);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(flags);
    size += ros::serialization::serializationLength(estop);
    return size;
  }

  typedef boost::shared_ptr< ::clearpath_horizon::SafetyStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::SafetyStatus_<ContainerAllocator>  const> ConstPtr;
}; // struct SafetyStatus
typedef  ::clearpath_horizon::SafetyStatus_<std::allocator<void> > SafetyStatus;

typedef boost::shared_ptr< ::clearpath_horizon::SafetyStatus> SafetyStatusPtr;
typedef boost::shared_ptr< ::clearpath_horizon::SafetyStatus const> SafetyStatusConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::SafetyStatus_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::SafetyStatus_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::SafetyStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cf78d6042b92d64ebda55641e06d66fa";
  }

  static const char* value(const  ::clearpath_horizon::SafetyStatus_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcf78d6042b92d64eULL;
  static const uint64_t static_value2 = 0xbda55641e06d66faULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::SafetyStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/SafetyStatus";
  }

  static const char* value(const  ::clearpath_horizon::SafetyStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::SafetyStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint16 flags\n\
bool estop\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::SafetyStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::SafetyStatus_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::SafetyStatus_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::SafetyStatus_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.flags);
    stream.next(m.estop);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SafetyStatus_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::SafetyStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::SafetyStatus_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "flags: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.flags);
    s << indent << "estop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.estop);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_SAFETYSTATUS_H

